<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>setText_Address</name>
   <tag></tag>
   <elementGuidId>b16749c8-d3a1-4490-8dfc-f0dc3248557e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Relative_adress-297</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Relative_adress-297']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b224c58c-d1d5-4d08-812e-10908c1c6ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5ca868b8-81e3-4293-b66e-e70f30899640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid </value>
      <webElementGuid>e8522e25-105f-4777-8a15-1fadb1e060c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6cd66d7a-edec-48ad-9ab3-863f7bdb49ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Relative_adress-297</value>
      <webElementGuid>2f2974fb-a1d1-456d-9a90-0b931d32dce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Relative_adress-297</value>
      <webElementGuid>0ca54424-6d53-4cd0-9f0f-14c2cf502471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>Relative_adress</value>
      <webElementGuid>15e6e14b-34e9-441b-976b-948f655ae8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Relative_adress-297&quot;)</value>
      <webElementGuid>ed78b475-b4db-4269-9990-d6df4099a451</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Relative_adress-297']</value>
      <webElementGuid>6bbda9de-ef0d-47c7-a2e7-72129ad44132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_Relative_adress']/div[2]/input</value>
      <webElementGuid>2d2059b7-eb01-4174-b9ba-4c734b33dc77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>950f4b61-2ccb-45bb-9883-b4c96a2068dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Relative_adress-297' and @id = 'Relative_adress-297']</value>
      <webElementGuid>6d60929f-4d42-4e71-91f2-ac25c3de035a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
