<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>setText_PasswordRegister</name>
   <tag></tag>
   <elementGuidId>f6c1dc2d-46a0-449a-895f-b8dc26cb77d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_password-297</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f437512-a77c-4b94-984d-e4c81842e22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid</value>
      <webElementGuid>d7565eb6-ad37-472a-bf58-b127d3d9efa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f6a2dd98-9c2d-4875-aa1f-bb3c55253936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_password-297</value>
      <webElementGuid>b2ac4d2e-1b84-451e-9fc4-00bb81ed7ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_password-297</value>
      <webElementGuid>34527ee1-c51b-4e25-a1fe-568d79e15f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>user_password</value>
      <webElementGuid>617912c8-ae1c-4fac-b9a5-f1183c61a782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_password-297&quot;)</value>
      <webElementGuid>ba8573ed-6460-4f4e-9a10-8d0d4642154e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_password-297']</value>
      <webElementGuid>fe100611-b152-4a1c-90d0-8dec39867c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_user_password']/div[2]/input</value>
      <webElementGuid>7b92d5ed-e121-44ea-b065-6ae41a43e593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>dfc08044-8d8b-4667-9f2e-589549483aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'user_password-297' and @id = 'user_password-297']</value>
      <webElementGuid>d8ad8ba7-23ef-48be-9bf2-d56571f74fdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
