<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>setText_UsernameRegister</name>
   <tag></tag>
   <elementGuidId>249f443c-fb58-4dcb-aaec-49d53ca1e7e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_login-297</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_login-297']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>276b28d9-38f7-4993-a80c-6c538ef348be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d12f6386-2ba7-47f9-aa6e-29f5df9ef2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid </value>
      <webElementGuid>14a17229-9934-410d-bd0d-d1a2def8a34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8b0d3ec-4e61-4dcb-b987-cc95373d8c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_login-297</value>
      <webElementGuid>622d3ccb-fadf-4db6-8fba-153a92a64e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_login-297</value>
      <webElementGuid>4de83c9b-13ff-4899-bb41-29a9bf298e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>unique_username</value>
      <webElementGuid>21c8b916-cb3b-4d07-b071-15f5f4ff3d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>user_login</value>
      <webElementGuid>8e38460d-df4b-4d88-b28e-cf29ec6a01ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_login-297&quot;)</value>
      <webElementGuid>2f7e09c1-6860-4c1c-9a00-344d56b6ef04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_login-297']</value>
      <webElementGuid>182a93bd-f884-4b68-b766-e7f7b09c1a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_user_login']/div[2]/input</value>
      <webElementGuid>3a6b162c-dc42-4449-956b-48e02eb52981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>02b5f813-5a48-47f7-9eee-3686ebe2b6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'user_login-297' and @id = 'user_login-297']</value>
      <webElementGuid>1f326342-4512-46a5-a77a-300c9cb626ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
