<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_BRI</name>
   <tag></tag>
   <elementGuidId>c89c772d-23f5-4a24-8ddf-a2d10ff4dec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment_method_xendit_briva</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_method_xendit_briva']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2638c659-71b7-4cbb-a9a8-66ea7fefcb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_method_xendit_briva</value>
      <webElementGuid>ce5af59e-b7b4-425e-bd12-0d6c8e07aa4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8a4509d9-38ed-4a2a-b0c2-6cd7caf5fe5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>b56c948d-539c-4f52-8484-012e10c1dac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>7dbd3744-362d-4be4-bc6f-39aa562764e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>xendit_briva</value>
      <webElementGuid>f7dced25-dd94-49e0-bd72-18c9e984c6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method_xendit_briva&quot;)</value>
      <webElementGuid>123ca95c-199d-4173-9996-537a73b9bd6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_method_xendit_briva']</value>
      <webElementGuid>a21b2c9f-6e8a-40ce-89f3-619309d485f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/ul/li[3]/input</value>
      <webElementGuid>5d2d4eea-cba6-4648-a140-ce4303cea2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>5c841768-0269-4c23-82a4-43b4c3abc49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_xendit_briva' and @type = 'radio' and @name = 'payment_method']</value>
      <webElementGuid>337ec8bd-df9f-4b3d-a661-b08fbc15895d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
